"""Revora Core Module."""
from backend.app.core.constants import (
    PaymentRail,
    PaymentStatus,
    FailureCode,
    FailureSource,
    MandateStatus,
    CustomerLanguage,
    ActionType,
    ActionOutcome,
    RiskTier,
    EvaluationSplit,
    MAX_RECOVERY_ATTEMPTS_PER_PAYMENT,
    MIN_RETRY_COOLDOWN_HOURS,
    MAX_AUTOMATED_ESCALATIONS,
    MAX_FAILED_RECOVERY_CYCLES,
    MAX_UPI_AUTOPAY_WITHOUT_AFA_INR,
)

__all__ = [
    "PaymentRail",
    "PaymentStatus",
    "FailureCode",
    "FailureSource",
    "MandateStatus",
    "CustomerLanguage",
    "ActionType",
    "ActionOutcome",
    "RiskTier",
    "EvaluationSplit",
    "MAX_RECOVERY_ATTEMPTS_PER_PAYMENT",
    "MIN_RETRY_COOLDOWN_HOURS",
    "MAX_AUTOMATED_ESCALATIONS",
    "MAX_FAILED_RECOVERY_CYCLES",
    "MAX_UPI_AUTOPAY_WITHOUT_AFA_INR",
]
